/* autogenerated by Processing revision 1310 on 2025-10-21 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import ddf.minim.*;
import ddf.minim.analysis.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class MusicVisualizer extends PApplet {




Minim minim;
AudioPlayer song;
FFT fft;
BeatDetect beat;

ArrayList<Float> amplitudeHistory = new ArrayList<Float>();
float rotationAngle = 0;
int[] gradientColors;

public void setup() {
  /* size commented out by preprocessor */;
  minim = new Minim(this);
  song = minim.loadFile("your_audio.mp3", 1024); // Replace with your audio file
  fft = new FFT(song.bufferSize(), song.sampleRate());
  beat = new BeatDetect();
  song.play();

  // Create a color gradient from blue to pink
  gradientColors = new int[fft.specSize()];
  for (int i = 0; i < gradientColors.length; i++) {
    float t = map(i, 0, gradientColors.length, 0, 1);
    gradientColors[i] = lerpColor(color(0, 100, 255), color(255, 0, 150), t);
  }
}

public void draw() {
  background(0);
  fft.forward(song.mix);
  beat.detect(song.mix);

  float amplitude = song.mix.level();
  amplitudeHistory.add(amplitude);
  if (amplitudeHistory.size() > width) {
    amplitudeHistory.remove(0);
  }

  // Rotate slowly, faster on beat
  float rotationSpeed = beat.isOnset() ? 0.05f : 0.01f;
  rotationAngle += rotationSpeed;

  pushMatrix();
  translate(width / 2, height / 2);
  rotate(rotationAngle);
  drawCircularSpectrum();
  popMatrix();

  drawAmplitudeTrail();
}

public void drawCircularSpectrum() {
  noFill();
  beginShape();
  for (int i = 0; i < fft.specSize(); i++) {
    float angle = map(i, 0, fft.specSize(), 0, TWO_PI);
    float bandValue = fft.getBand(i);
    float radius = 150 + bandValue * 2;
    float x = cos(angle) * radius;
    float y = sin(angle) * radius;

    stroke(gradientColors[i]);
    vertex(x, y);
  }
  endShape(CLOSE);
}

public void drawAmplitudeTrail() {
  noFill();
  stroke(0, 255, 0);
  beginShape();
  for (int i = 0; i < amplitudeHistory.size(); i++) {
    float y = map(amplitudeHistory.get(i), 0, 0.5f, height, height - 100);
    vertex(i, y);
  }
  endShape();
}


  public void settings() { size(800, 600); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "MusicVisualizer" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
